### ISSUE TITLE
Facing issues while running run.sh

### ISSUE THREAD

**Issue by rajaswa** [stanojevic/rotating-ccg#1]
After completing the setup exactly as mentioned in the README, I am running the following command:
```bash
"./scripts/run.sh" "edin.ccg.MainParse" \ --model_dirs model \ --beam-parsing 1 \ --input_file input.sentences \ --output_file output.trees
```

The content of my `input.sentences` file is as follows:
```
It's been a while since I last ate Ice-cream!
It's a lovely day.
```

The parser does not seem to be running perfectly for me, and I am facing this exception:
```bash
Starting ELMo server START
using port 9002 for ELMo
Exception in thread "main" org.apache.thrift.TApplicationException: Internal error
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at edin.nn.embedder.SequenceEmbedderELMo_Service$Client.recv_start_elmo(SequenceEmbedderELMo_Service.java:68)
	at edin.nn.embedder.SequenceEmbedderELMo_Service$Client.start_elmo(SequenceEmbedderELMo_Service.java:56)
	at edin.nn.embedder.SequenceEmbedderELMo$.elmo_service(SequenceEmbedderELMo.scala:152)
	at edin.nn.embedder.SequenceEmbedderELMo$.embed_sents(SequenceEmbedderELMo.scala:127)
	at edin.nn.embedder.SequenceEmbedderELMo.embedSents(SequenceEmbedderELMo.scala:244)
	at edin.nn.embedder.SequenceEmbedderELMo.embedSent(SequenceEmbedderELMo.scala:238)
	at edin.nn.embedder.SequenceEmbedderELMo.transduce(SequenceEmbedderELMo.scala:209)
	at edin.nn.embedder.SequenceEmbedderBiRecurrent.transduce(SequenceEmbedderBiRecurrent.scala:39)
	at edin.ccg.parsing.Parser$.initParserState(Parser.scala:76)
	at edin.ccg.MainParse$.$anonfun$main$4(MainParse.scala:86)
	at scala.collection.immutable.List.map(List.scala:283)
	at edin.ccg.MainParse$.$anonfun$main$3(MainParse.scala:86)
	at edin.ccg.MainParse$.$anonfun$main$3$adapted(MainParse.scala:73)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at edin.ccg.MainParse$.main(MainParse.scala:73)
	at edin.ccg.MainParse.main(MainParse.scala)
```

Is there something wrong with the format of my `input.sentences` file? How do I get around this issue?

**Comment by stanojevic** [comment]
I tried the sentences you gave and it works on my computer. It's probably something wrong with the installation, not with the input, but I can't really point to anything specific. I'd first try to test if ELMo works directly from python installation and whether the right version of allennlp is installed.
Other than that, to get a good quality parse you should tokenize sentences before you give them to the parser. In your example 's and ! should be separated from other tokens. You can do these things automatically with stanford's core-nlp package or any other package that does penn tokenization. That is not the cause of the crash though.

**Comment by rajaswa** [comment]
It turns out my installation was actually correct! There seems to be some issue with AllenNLP, which affects all its versions (new and old). See: https://github.com/allenai/allennlp/issues/5203 https://github.com/allenai/allennlp/issues/5197

This can be solved by downgrading the `overrides` package to `3.1.0` after all the python dependencies mentioned in the README are installed:
```bash
pip install overrides==3.1.0
```

Thank you for pointing out the Penn tokenization issue! The parser is running perfectly well now.

**Comment by PonyCheng** [comment]
> It turns out my installation was actually correct! There seems to be some issue with AllenNLP, which affects all its versions (new and old). See: [allenai/allennlp#5203](https://github.com/allenai/allennlp/issues/5203) [allenai/allennlp#5197](https://github.com/allenai/allennlp/issues/5197)
> 
> This can be solved by downgrading the `overrides` package to `3.1.0` after all the python dependencies mentioned in the README are installed:
> 
> ```shell
> pip install overrides==3.1.0
> ```
> 
> Thank you for pointing out the Penn tokenization issue! The parser is running perfectly well now.

Hi, I meet the same issue (when _using port 9004 for ELMo_ ). can you share the version of your packages?

**Comment by stanojevic** [comment]
These are the versions on my machine:
'scikit-learn==0.22.1' 'overrides==3.1.0' 'allennlp==0.4.2' 'thrift==0.11.0'  'torch-0.3.1' 

Try running ELMo from python's repl and see if it crashes with this:

from allennlp.commands.elmo import ElmoEmbedder
elmo = ElmoEmbedder()
print(elmo.embed_sentence("Hellow there".split()))
